obj-m += rwProcMemHwbp_module.o
rwProcMemHwbp_module-objs := rwProcMem_module.o hwbp_module.o cvector.o

ccflags-y += -I$(src) \
  -I$(src)/../rwProcMem33Module/rwProcMem_module \
  -I$(src)/../hwBreakpointProcModule/hwBreakpointProc_module
